WITH CTE AS (
SELECT ID, CHIEF_ID, 1 AS Depth
From Employee
WHERE CHIEF_ID IS NULL
UNION ALL
SELECT e.ID, e.CHIEF_ID, c.Depth + 1
FROM Employee e
JOIN CTE c ON e.CHIEF_ID = c.ID
)
SELECT MAX(DEPTH) FROM CTE
